# Generated by Django 4.1.7 on 2023-04-02 08:17

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilesCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=pathlib.PurePosixPath(
                            "/home/denis/Projects/personal/django-adverity/files"
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generation_time", models.FloatField()),
            ],
        ),
    ]
